version: '3.4'

services:
  testrabbitmq:
    image: ${DOCKER_REGISTRY-}testrabbitmq
    build:
      context: .
      dockerfile: TestRabbitmq/Dockerfile
    depends_on:
      - rabbitmq
      - postgres
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=user;Server=postgres;Port=5432;Database=testRabbitMQ;Pooling=true;
      - RabbitMQ__HostName=rabbitmq
      - RabbitMQ__UserName=guest
      - RabbitMQ__Password=guest
      - RabbitMQ__Port=5672
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_management && rabbitmq-server"
    networks:
      - mynetwork

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: user
      POSTGRES_DB: testRabbitMQ
    ports:
      - "5432:5432"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
